version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/jesseduffield/lazygit
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            ./test.sh
      - run:
          name: Push on codecov result
          command: |
            bash <(curl -s https://codecov.io/bash)

  release:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/jesseduffield/lazygit
    steps:
      - checkout
      - run:
          name: Run gorelease
          command: |
            curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build:
    jobs:
      - build
  release:
    jobs:
      - release:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
